# Generated by Django 4.2.7 on 2023-11-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista', '0002_investimento_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='nivel',
        ),
    ]
